#!/bin/python

import os
import shutil

os.chdir("./build/")
shutil.rmtree("shaders")
shutil.rmtree("assets")
shutil.copytree("../shaders", "shaders")
shutil.copytree("../assets", "assets")
os.system("cmake -G Ninja ..")
os.system("ninja")
